config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :pins do
    member do
      put "like", to: "pins#upvote"
    end
  end

  root 'pins#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pin.rb
class Pin < ApplicationRecord
  acts_as_votable
  belongs_to :user
  validates :title, :description, :picture, presence: true

  mount_uploader :picture, PinPictureUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :find_pin, only: [:show, :edit, :update, :destroy, :upvote]
  before_action :authenticate_user!, except: [:index, :show]

  def index
  @pins = Pin.all.order("created_at DESC")
  end

  def show
  end

  def new
    @pin = current_user.pins.build
  end

  def create
    @pin = current_user.pins.build(pin_params)
    if @pin.save
      redirect_to @pin, notice: "Successfully created a new Pin yo"
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @pin.update(pin_params)
      redirect_to @pin, notice: "Pin be updated yo!"
    else
      render 'edit'
    end
  end

  def destroy
    @pin.destroy
    redirect_to root_path
  end

  def upvote
    @pin.upvote_by current_user
    redirect_to :back
  end

  private
  def pin_params
    params.require(:pin).permit(:title, :description, :picture)
  end

  def find_pin
    @pin = Pin.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/_navbar.html.erb
<!-- Fixed navbar -->
 <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
   <div class="container">
     <div class="navbar-header">
       <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
         <span class="sr-only">Toggle navigation</span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
       </button>
       <div class="small-logo-container">
         <%= link_to "Pinteresting", root_path, class: "small-logo"%>
       </div>
     </div>
     <div class="navbar-collapse collapse">

       <ul class="nav navbar-nav navbar-right">
         <li><%= link_to "Home", root_path %></li>
         <li><%= link_to "New Pin", new_pin_path %></li>
         <li><%= link_to "Account", edit_user_registration_path %></li>
         <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
       </ul>
     </div><!--/.nav-collapse -->
   </div>
 </div>

 <div class="container-fluid big-logo-row">
   <div class="container">
     <div class="row">
       <div class="col-xs-12 big-logo-container">
         <h1 class="big-logo">Pinteresting</h1>
       </div><!--/.col-xs-12 -->
     </div><!--/.row -->
   </div><!--/.container -->
 </div><!--/.container-fluid -->
 <br>

app/views/layouts/_navbar_anonymous_user.html.erb
<!-- Fixed navbar -->
 <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
   <div class="container">
     <div class="navbar-header">
       <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
         <span class="sr-only">Toggle navigation</span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
       </button>
       <div class="small-logo-container">
         <%= link_to "Pinteresting", root_path, class: "small-logo"%>
       </div>
     </div>
     <div class="navbar-collapse collapse">

       <ul class="nav navbar-nav navbar-right">
         <li><%= link_to "Sign up", new_user_registration_path %></li>
         <li><%= link_to "Sign in", new_user_session_path %></li>
       </ul>
     </div><!--/.nav-collapse -->
   </div>
 </div>

 <div class="container-fluid big-logo-row">
   <div class="container">
     <div class="row">
       <div class="col-xs-12 big-logo-container">
         <h1 class="big-logo">Pinteresting</h1>
       </div><!--/.col-xs-12 -->
     </div><!--/.row -->
   </div><!--/.container -->
 </div><!--/.container-fluid -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pinteresting Clone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
      <%= render 'layouts/navbar' %>
    <% else %>
      <%= render 'layouts/navbar_anonymous_user' %>
    <% end %>

    <div class="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, class: "alert alert-info" %>
      <% end %>

      <%= yield %>
    </div>
    
  </body>
</html>

app/views/pins/_form.html.erb
<%= simple_form_for @pin, html: {multipart: true} do |f| %>
  <% if @pin.errors.any? %>
    <div id="errors">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this Pin from being saved:</h2>
      <ul>
        <% @pin.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
  </div>
  <% end %>

  <div class="form-group">
    <%= f.input :title, input_html: {class: 'form-control'} %>
    <%= f.input :description, input_html: {class: 'form-control'} %>
    <%= f.hidden_field(:picture_cache) %>
    <%= f.input :picture, input_html: {class: 'form-control'}  %>
  </div>

  <div class="btn-group">
    <%= f.button :submit, class: "btn btn-default" %>
  </div>

<% end %>

app/views/pins/edit.html.erb
<div class="col-md-6 col-md-offset-3">
  <h1>Edit Pin</h1>
    <img class="card-img-top" src="<%= @pin.picture %>" alt="Profile Image" width="100%">
    <%= render 'form' %>
    

app/views/pins/index.html.erb
<div id="pins" class="transitions-enabled">
  <% @pins.each do |pin| %>
    <div class="box panel panel-default">
      <%= link_to (image_tag pin.picture.url), pin %>
        <div class="panel-body">
          <div class="card-block">
            <h2 class="card-title"><%= link_to pin.title, pin %></h2>
            <p class="card-text"><%= pin.description %></p>
            <p class="card-text"><small class="text-muted">Posted by <%= pin.user.email %></p></small>
          </div>
        </div>
      </div>
  <% end %>
</div>

app/views/pins/index.html.slim
doctype html
html
  head
    title Slim Examples

  body
    h1 THIS IS THE IMAGE PLACEHOLDER

app/views/pins/new.html.erb
<div class="col-md-6 col-md-offset-3">
  <h1>Create a pin, Pinhead</h1>
  <%= render 'form' %>

  <%= link_to "Back", root_path %>
</div>

app/views/pins/show.html.erb
<br>
<div class="row" id="pin_show">
  <div class="col-md-6 col-md-offset-3">
    <div class="panel panel-default">
      <div class="panel-heading pin_image">
        <%= image_tag @pin.picture.url %>
      </div>
      <div class="panel-body">
        <div class="card-block">
          <h1>
            <%= @pin.title %>
          </h1>
          <p class="description">
            <%= @pin.description %>
          </p>
          <p class="card-text"><small class="text-muted">Created <%= time_ago_in_words(@pin.created_at) %> ago</small></p>
          <div class="btn-group">
            <%= link_to like_pin_path(@pin), method: :put, class: "btn btn-default" do %>
            <span class="glyphicon glyphicon-heart"></span>
            <%= @pin.get_upvotes.size %>
            <% end %>
            <% if user_signed_in? %>
              <%= link_to "Edit", edit_pin_path, class: "btn btn-default" %>
              <%= link_to "Delete", pin_path, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-default" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>